name: Inputs Demo
on: 
  workflow_dispatch:
    inputs:
      environments:
        description: Chose the environment to deply
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - prod
      artifact_tag:
        description: Choose the git tag to deploy
        required: true
jobs:
    inputs-demo:
      runs-on: ubuntu-latest
      steps:
        - name: Deply the App
          run: echo "Deploying the ${{ inputs.artifact_tag }} application to ${{ inputs.environments }}"
