name: Or Condition Demo
on: 
  push:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Run for Kings or kingsleychino
        if: github.actor == 'Kings' || github.actor == 'kingsleychino'
        run: echo "It is triggered by either Kings or Chino"
